"""Optional reasoning auxiliary head for KothaGPT."""

from __future__ import annotations


class ReasoningHead:
    """Supervised decoder head predicting solution steps.

    Used during training for auxiliary supervision. Not used at
    inference; chain-of-thought is generated by the base LM head.
    """

    def __init__(self, hidden_size: int, vocab_size: int,
                 num_layers: int = 2):
        self.hidden_size = hidden_size
        self.vocab_size = vocab_size
        self.num_layers = num_layers

    def forward(self, hidden_states):
        """Predict solution step tokens."""
        raise NotImplementedError

    def loss(self, hidden_states, target_tokens) -> float:
        """Compute auxiliary reasoning loss."""
        raise NotImplementedError
